version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
    volumes:
      - .:/app
    command: gunicorn --bind 0.0.0.0:8000 --workers 4 run:app