version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=run.py
      - PYTHONUNBUFFERED=1
      - OPENCV_VIDEOIO_DEBUG=1
      - OPENCV_LOG_LEVEL=DEBUG
      - GST_DEBUG=3
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/home/appuser/.Xauthority:rw
    privileged: true
    network_mode: "host"  # Use host networking
    extra_hosts:
      - "host.docker.internal:host-gateway"
    devices:
      - /dev/video0:/dev/video0
    command: >
      gunicorn
      --bind 0.0.0.0:8000
      --worker-class gthread
      --workers 1
      --threads 4
      --timeout 120
      --log-level debug
      "run:app"